2013-08-24 15:34:29,665 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongoDatastore': FactoryBean threw exception on object creation; nested exception is org.springframework.dao.DataAccessResourceFailureException: Read operation to server /127.0.0.1:27017 failed on database petiko; nested exception is com.mongodb.MongoException$Network: Read operation to server /127.0.0.1:27017 failed on database petiko
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:149)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:102)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1442)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:305)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.BeanFactory$getBean.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.grails.datastore.gorm.plugin.support.PersistenceContextInterceptorAggregator.postProcessBeanFactory(PersistenceContextInterceptorAggregator.groovy:109)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:687)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:626)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:454)
	at org.codehaus.groovy.grails.commons.spring.DefaultRuntimeSpringConfiguration.getApplicationContext(DefaultRuntimeSpringConfiguration.java:153)
	at org.codehaus.groovy.grails.commons.spring.GrailsRuntimeConfigurator.configure(GrailsRuntimeConfigurator.java:170)
	at org.codehaus.groovy.grails.commons.spring.GrailsRuntimeConfigurator.configure(GrailsRuntimeConfigurator.java:127)
	at org.codehaus.groovy.grails.web.context.GrailsConfigUtils.configureWebApplicationContext(GrailsConfigUtils.java:121)
	at org.codehaus.groovy.grails.web.context.GrailsContextLoader.initWebApplicationContext(GrailsContextLoader.java:107)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:111)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4939)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5434)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)
Caused by: org.springframework.dao.DataAccessResourceFailureException: Read operation to server /127.0.0.1:27017 failed on database petiko; nested exception is com.mongodb.MongoException$Network: Read operation to server /127.0.0.1:27017 failed on database petiko
	at org.springframework.data.mongodb.core.MongoExceptionTranslator.translateExceptionIfPossible(MongoExceptionTranslator.java:56)
	at org.springframework.data.mongodb.core.MongoTemplate.potentiallyConvertRuntimeException(MongoTemplate.java:1666)
	at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:374)
	at org.grails.datastore.mapping.mongo.MongoDatastore.initializeIndices(MongoDatastore.java:286)
	at org.grails.datastore.mapping.mongo.MongoDatastore.createMongoTemplate(MongoDatastore.java:277)
	at org.grails.datastore.mapping.mongo.MongoDatastore.afterPropertiesSet(MongoDatastore.java:222)
	at org.springframework.beans.factory.InitializingBean$afterPropertiesSet.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at org.grails.datastore.gorm.mongo.bean.factory.MongoDatastoreFactoryBean.getObject(MongoDatastoreFactoryBean.groovy:53)
	at org.grails.datastore.gorm.mongo.bean.factory.MongoDatastoreFactoryBean.getObject(MongoDatastoreFactoryBean.groovy)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:142)
	... 28 more
Caused by: com.mongodb.MongoException$Network: Read operation to server /127.0.0.1:27017 failed on database petiko
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:253)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:216)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:288)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:273)
	at com.mongodb.DBCollection.findOne(DBCollection.java:728)
	at com.mongodb.DBCollection.findOne(DBCollection.java:670)
	at com.mongodb.DBApiLayer$MyCollection.createIndex(DBApiLayer.java:342)
	at com.mongodb.DBCollection.createIndex(DBCollection.java:485)
	at com.mongodb.DBCollection.ensureIndex(DBCollection.java:561)
	at com.mongodb.DBCollection.ensureIndex(DBCollection.java:512)
	at org.grails.datastore.mapping.mongo.MongoDatastore$6.doInDB(MongoDatastore.java:322)
	at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:372)
	... 38 more
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at com.mongodb.DBPort._open(DBPort.java:223)
	at com.mongodb.DBPort.go(DBPort.java:125)
	at com.mongodb.DBPort.call(DBPort.java:92)
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:244)
	... 49 more
2013-08-24 15:34:29,673 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
org.springframework.dao.DataAccessResourceFailureException: Read operation to server /127.0.0.1:27017 failed on database petiko; nested exception is com.mongodb.MongoException$Network: Read operation to server /127.0.0.1:27017 failed on database petiko
	at org.springframework.data.mongodb.core.MongoExceptionTranslator.translateExceptionIfPossible(MongoExceptionTranslator.java:56)
	at org.springframework.data.mongodb.core.MongoTemplate.potentiallyConvertRuntimeException(MongoTemplate.java:1666)
	at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:374)
	at org.grails.datastore.mapping.mongo.MongoDatastore.initializeIndices(MongoDatastore.java:286)
	at org.grails.datastore.mapping.mongo.MongoDatastore.createMongoTemplate(MongoDatastore.java:277)
	at org.grails.datastore.mapping.mongo.MongoDatastore.afterPropertiesSet(MongoDatastore.java:222)
	at org.springframework.beans.factory.InitializingBean$afterPropertiesSet.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at org.grails.datastore.gorm.mongo.bean.factory.MongoDatastoreFactoryBean.getObject(MongoDatastoreFactoryBean.groovy:53)
	at org.grails.datastore.gorm.mongo.bean.factory.MongoDatastoreFactoryBean.getObject(MongoDatastoreFactoryBean.groovy)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:142)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:102)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1442)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:305)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.BeanFactory$getBean.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.grails.datastore.gorm.plugin.support.PersistenceContextInterceptorAggregator.postProcessBeanFactory(PersistenceContextInterceptorAggregator.groovy:109)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:687)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:626)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:454)
	at org.codehaus.groovy.grails.commons.spring.DefaultRuntimeSpringConfiguration.getApplicationContext(DefaultRuntimeSpringConfiguration.java:153)
	at org.codehaus.groovy.grails.commons.spring.GrailsRuntimeConfigurator.configure(GrailsRuntimeConfigurator.java:170)
	at org.codehaus.groovy.grails.commons.spring.GrailsRuntimeConfigurator.configure(GrailsRuntimeConfigurator.java:127)
	at org.codehaus.groovy.grails.web.context.GrailsConfigUtils.configureWebApplicationContext(GrailsConfigUtils.java:121)
	at org.codehaus.groovy.grails.web.context.GrailsContextLoader.initWebApplicationContext(GrailsContextLoader.java:107)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:111)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4939)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5434)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)
Caused by: com.mongodb.MongoException$Network: Read operation to server /127.0.0.1:27017 failed on database petiko
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:253)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:216)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:288)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:273)
	at com.mongodb.DBCollection.findOne(DBCollection.java:728)
	at com.mongodb.DBCollection.findOne(DBCollection.java:670)
	at com.mongodb.DBApiLayer$MyCollection.createIndex(DBApiLayer.java:342)
	at com.mongodb.DBCollection.createIndex(DBCollection.java:485)
	at com.mongodb.DBCollection.ensureIndex(DBCollection.java:561)
	at com.mongodb.DBCollection.ensureIndex(DBCollection.java:512)
	at org.grails.datastore.mapping.mongo.MongoDatastore$6.doInDB(MongoDatastore.java:322)
	at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:372)
	... 38 more
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at com.mongodb.DBPort._open(DBPort.java:223)
	at com.mongodb.DBPort.go(DBPort.java:125)
	at com.mongodb.DBPort.call(DBPort.java:92)
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:244)
	... 49 more
2013-08-24 15:34:29,674 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
com.mongodb.MongoException$Network: Read operation to server /127.0.0.1:27017 failed on database petiko
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:253)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:216)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:288)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:273)
	at com.mongodb.DBCollection.findOne(DBCollection.java:728)
	at com.mongodb.DBCollection.findOne(DBCollection.java:670)
	at com.mongodb.DBApiLayer$MyCollection.createIndex(DBApiLayer.java:342)
	at com.mongodb.DBCollection.createIndex(DBCollection.java:485)
	at com.mongodb.DBCollection.ensureIndex(DBCollection.java:561)
	at com.mongodb.DBCollection.ensureIndex(DBCollection.java:512)
	at org.grails.datastore.mapping.mongo.MongoDatastore$6.doInDB(MongoDatastore.java:322)
	at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:372)
	at org.grails.datastore.mapping.mongo.MongoDatastore.initializeIndices(MongoDatastore.java:286)
	at org.grails.datastore.mapping.mongo.MongoDatastore.createMongoTemplate(MongoDatastore.java:277)
	at org.grails.datastore.mapping.mongo.MongoDatastore.afterPropertiesSet(MongoDatastore.java:222)
	at org.springframework.beans.factory.InitializingBean$afterPropertiesSet.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at org.grails.datastore.gorm.mongo.bean.factory.MongoDatastoreFactoryBean.getObject(MongoDatastoreFactoryBean.groovy:53)
	at org.grails.datastore.gorm.mongo.bean.factory.MongoDatastoreFactoryBean.getObject(MongoDatastoreFactoryBean.groovy)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:142)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:102)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1442)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:305)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.BeanFactory$getBean.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.grails.datastore.gorm.plugin.support.PersistenceContextInterceptorAggregator.postProcessBeanFactory(PersistenceContextInterceptorAggregator.groovy:109)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:687)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:626)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:454)
	at org.codehaus.groovy.grails.commons.spring.DefaultRuntimeSpringConfiguration.getApplicationContext(DefaultRuntimeSpringConfiguration.java:153)
	at org.codehaus.groovy.grails.commons.spring.GrailsRuntimeConfigurator.configure(GrailsRuntimeConfigurator.java:170)
	at org.codehaus.groovy.grails.commons.spring.GrailsRuntimeConfigurator.configure(GrailsRuntimeConfigurator.java:127)
	at org.codehaus.groovy.grails.web.context.GrailsConfigUtils.configureWebApplicationContext(GrailsConfigUtils.java:121)
	at org.codehaus.groovy.grails.web.context.GrailsContextLoader.initWebApplicationContext(GrailsContextLoader.java:107)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:111)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4939)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5434)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at com.mongodb.DBPort._open(DBPort.java:223)
	at com.mongodb.DBPort.go(DBPort.java:125)
	at com.mongodb.DBPort.call(DBPort.java:92)
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:244)
	... 49 more
2013-08-24 15:34:29,675 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at com.mongodb.DBPort._open(DBPort.java:223)
	at com.mongodb.DBPort.go(DBPort.java:125)
	at com.mongodb.DBPort.call(DBPort.java:92)
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:244)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:216)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:288)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:273)
	at com.mongodb.DBCollection.findOne(DBCollection.java:728)
	at com.mongodb.DBCollection.findOne(DBCollection.java:670)
	at com.mongodb.DBApiLayer$MyCollection.createIndex(DBApiLayer.java:342)
	at com.mongodb.DBCollection.createIndex(DBCollection.java:485)
	at com.mongodb.DBCollection.ensureIndex(DBCollection.java:561)
	at com.mongodb.DBCollection.ensureIndex(DBCollection.java:512)
	at org.grails.datastore.mapping.mongo.MongoDatastore$6.doInDB(MongoDatastore.java:322)
	at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:372)
	at org.grails.datastore.mapping.mongo.MongoDatastore.initializeIndices(MongoDatastore.java:286)
	at org.grails.datastore.mapping.mongo.MongoDatastore.createMongoTemplate(MongoDatastore.java:277)
	at org.grails.datastore.mapping.mongo.MongoDatastore.afterPropertiesSet(MongoDatastore.java:222)
	at org.springframework.beans.factory.InitializingBean$afterPropertiesSet.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at org.grails.datastore.gorm.mongo.bean.factory.MongoDatastoreFactoryBean.getObject(MongoDatastoreFactoryBean.groovy:53)
	at org.grails.datastore.gorm.mongo.bean.factory.MongoDatastoreFactoryBean.getObject(MongoDatastoreFactoryBean.groovy)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:142)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:102)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1442)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:305)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.BeanFactory$getBean.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.grails.datastore.gorm.plugin.support.PersistenceContextInterceptorAggregator.postProcessBeanFactory(PersistenceContextInterceptorAggregator.groovy:109)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:687)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:626)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:454)
	at org.codehaus.groovy.grails.commons.spring.DefaultRuntimeSpringConfiguration.getApplicationContext(DefaultRuntimeSpringConfiguration.java:153)
	at org.codehaus.groovy.grails.commons.spring.GrailsRuntimeConfigurator.configure(GrailsRuntimeConfigurator.java:170)
	at org.codehaus.groovy.grails.commons.spring.GrailsRuntimeConfigurator.configure(GrailsRuntimeConfigurator.java:127)
	at org.codehaus.groovy.grails.web.context.GrailsConfigUtils.configureWebApplicationContext(GrailsConfigUtils.java:121)
	at org.codehaus.groovy.grails.web.context.GrailsContextLoader.initWebApplicationContext(GrailsContextLoader.java:107)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:111)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4939)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5434)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)
2013-08-24 15:34:29,676 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongoDatastore': FactoryBean threw exception on object creation; nested exception is org.springframework.dao.DataAccessResourceFailureException: Read operation to server /127.0.0.1:27017 failed on database petiko; nested exception is com.mongodb.MongoException$Network: Read operation to server /127.0.0.1:27017 failed on database petiko
	at org.grails.datastore.gorm.plugin.support.PersistenceContextInterceptorAggregator.postProcessBeanFactory(PersistenceContextInterceptorAggregator.groovy:109)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)
Caused by: org.springframework.dao.DataAccessResourceFailureException: Read operation to server /127.0.0.1:27017 failed on database petiko; nested exception is com.mongodb.MongoException$Network: Read operation to server /127.0.0.1:27017 failed on database petiko
	at org.grails.datastore.mapping.mongo.MongoDatastore.initializeIndices(MongoDatastore.java:286)
	at org.grails.datastore.mapping.mongo.MongoDatastore.createMongoTemplate(MongoDatastore.java:277)
	at org.grails.datastore.mapping.mongo.MongoDatastore.afterPropertiesSet(MongoDatastore.java:222)
	at org.grails.datastore.gorm.mongo.bean.factory.MongoDatastoreFactoryBean.getObject(MongoDatastoreFactoryBean.groovy:53)
	... 6 more
Caused by: com.mongodb.MongoException$Network: Read operation to server /127.0.0.1:27017 failed on database petiko
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:253)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:216)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:288)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:273)
	at com.mongodb.DBCollection.findOne(DBCollection.java:728)
	at com.mongodb.DBCollection.findOne(DBCollection.java:670)
	at com.mongodb.DBApiLayer$MyCollection.createIndex(DBApiLayer.java:342)
	at com.mongodb.DBCollection.createIndex(DBCollection.java:485)
	at com.mongodb.DBCollection.ensureIndex(DBCollection.java:561)
	at com.mongodb.DBCollection.ensureIndex(DBCollection.java:512)
	at org.grails.datastore.mapping.mongo.MongoDatastore$6.doInDB(MongoDatastore.java:322)
	... 10 more
Caused by: java.net.ConnectException: Connection refused
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at com.mongodb.DBPort._open(DBPort.java:223)
	at com.mongodb.DBPort.go(DBPort.java:125)
	at com.mongodb.DBPort.call(DBPort.java:92)
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:244)
	... 20 more
2013-08-24 15:34:29,677 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongoDatastore': FactoryBean threw exception on object creation; nested exception is org.springframework.dao.DataAccessResourceFailureException: Read operation to server /127.0.0.1:27017 failed on database petiko; nested exception is com.mongodb.MongoException$Network: Read operation to server /127.0.0.1:27017 failed on database petiko
	at org.grails.datastore.gorm.plugin.support.PersistenceContextInterceptorAggregator.postProcessBeanFactory(PersistenceContextInterceptorAggregator.groovy:109)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)
Caused by: org.springframework.dao.DataAccessResourceFailureException: Read operation to server /127.0.0.1:27017 failed on database petiko; nested exception is com.mongodb.MongoException$Network: Read operation to server /127.0.0.1:27017 failed on database petiko
	at org.grails.datastore.mapping.mongo.MongoDatastore.initializeIndices(MongoDatastore.java:286)
	at org.grails.datastore.mapping.mongo.MongoDatastore.createMongoTemplate(MongoDatastore.java:277)
	at org.grails.datastore.mapping.mongo.MongoDatastore.afterPropertiesSet(MongoDatastore.java:222)
	at org.grails.datastore.gorm.mongo.bean.factory.MongoDatastoreFactoryBean.getObject(MongoDatastoreFactoryBean.groovy:53)
	... 6 more
Caused by: com.mongodb.MongoException$Network: Read operation to server /127.0.0.1:27017 failed on database petiko
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:253)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:216)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:288)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:273)
	at com.mongodb.DBCollection.findOne(DBCollection.java:728)
	at com.mongodb.DBCollection.findOne(DBCollection.java:670)
	at com.mongodb.DBApiLayer$MyCollection.createIndex(DBApiLayer.java:342)
	at com.mongodb.DBCollection.createIndex(DBCollection.java:485)
	at com.mongodb.DBCollection.ensureIndex(DBCollection.java:561)
	at com.mongodb.DBCollection.ensureIndex(DBCollection.java:512)
	at org.grails.datastore.mapping.mongo.MongoDatastore$6.doInDB(MongoDatastore.java:322)
	... 10 more
Caused by: java.net.ConnectException: Connection refused
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at com.mongodb.DBPort._open(DBPort.java:223)
	at com.mongodb.DBPort.go(DBPort.java:125)
	at com.mongodb.DBPort.call(DBPort.java:92)
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:244)
	... 20 more
2013-08-24 15:34:29,678 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
org.springframework.dao.DataAccessResourceFailureException: Read operation to server /127.0.0.1:27017 failed on database petiko; nested exception is com.mongodb.MongoException$Network: Read operation to server /127.0.0.1:27017 failed on database petiko
	at org.grails.datastore.mapping.mongo.MongoDatastore.initializeIndices(MongoDatastore.java:286)
	at org.grails.datastore.mapping.mongo.MongoDatastore.createMongoTemplate(MongoDatastore.java:277)
	at org.grails.datastore.mapping.mongo.MongoDatastore.afterPropertiesSet(MongoDatastore.java:222)
	at org.grails.datastore.gorm.mongo.bean.factory.MongoDatastoreFactoryBean.getObject(MongoDatastoreFactoryBean.groovy:53)
	at org.grails.datastore.gorm.plugin.support.PersistenceContextInterceptorAggregator.postProcessBeanFactory(PersistenceContextInterceptorAggregator.groovy:109)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)
Caused by: com.mongodb.MongoException$Network: Read operation to server /127.0.0.1:27017 failed on database petiko
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:253)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:216)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:288)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:273)
	at com.mongodb.DBCollection.findOne(DBCollection.java:728)
	at com.mongodb.DBCollection.findOne(DBCollection.java:670)
	at com.mongodb.DBApiLayer$MyCollection.createIndex(DBApiLayer.java:342)
	at com.mongodb.DBCollection.createIndex(DBCollection.java:485)
	at com.mongodb.DBCollection.ensureIndex(DBCollection.java:561)
	at com.mongodb.DBCollection.ensureIndex(DBCollection.java:512)
	at org.grails.datastore.mapping.mongo.MongoDatastore$6.doInDB(MongoDatastore.java:322)
	... 10 more
Caused by: java.net.ConnectException: Connection refused
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at com.mongodb.DBPort._open(DBPort.java:223)
	at com.mongodb.DBPort.go(DBPort.java:125)
	at com.mongodb.DBPort.call(DBPort.java:92)
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:244)
	... 20 more
2013-08-24 15:34:29,678 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
com.mongodb.MongoException$Network: Read operation to server /127.0.0.1:27017 failed on database petiko
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:253)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:216)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:288)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:273)
	at com.mongodb.DBCollection.findOne(DBCollection.java:728)
	at com.mongodb.DBCollection.findOne(DBCollection.java:670)
	at com.mongodb.DBApiLayer$MyCollection.createIndex(DBApiLayer.java:342)
	at com.mongodb.DBCollection.createIndex(DBCollection.java:485)
	at com.mongodb.DBCollection.ensureIndex(DBCollection.java:561)
	at com.mongodb.DBCollection.ensureIndex(DBCollection.java:512)
	at org.grails.datastore.mapping.mongo.MongoDatastore$6.doInDB(MongoDatastore.java:322)
	at org.grails.datastore.mapping.mongo.MongoDatastore.initializeIndices(MongoDatastore.java:286)
	at org.grails.datastore.mapping.mongo.MongoDatastore.createMongoTemplate(MongoDatastore.java:277)
	at org.grails.datastore.mapping.mongo.MongoDatastore.afterPropertiesSet(MongoDatastore.java:222)
	at org.grails.datastore.gorm.mongo.bean.factory.MongoDatastoreFactoryBean.getObject(MongoDatastoreFactoryBean.groovy:53)
	at org.grails.datastore.gorm.plugin.support.PersistenceContextInterceptorAggregator.postProcessBeanFactory(PersistenceContextInterceptorAggregator.groovy:109)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)
Caused by: java.net.ConnectException: Connection refused
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at com.mongodb.DBPort._open(DBPort.java:223)
	at com.mongodb.DBPort.go(DBPort.java:125)
	at com.mongodb.DBPort.call(DBPort.java:92)
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:244)
	... 20 more
2013-08-24 15:34:29,679 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
java.net.ConnectException: Connection refused
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at com.mongodb.DBPort._open(DBPort.java:223)
	at com.mongodb.DBPort.go(DBPort.java:125)
	at com.mongodb.DBPort.call(DBPort.java:92)
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:244)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:216)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:288)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:273)
	at com.mongodb.DBCollection.findOne(DBCollection.java:728)
	at com.mongodb.DBCollection.findOne(DBCollection.java:670)
	at com.mongodb.DBApiLayer$MyCollection.createIndex(DBApiLayer.java:342)
	at com.mongodb.DBCollection.createIndex(DBCollection.java:485)
	at com.mongodb.DBCollection.ensureIndex(DBCollection.java:561)
	at com.mongodb.DBCollection.ensureIndex(DBCollection.java:512)
	at org.grails.datastore.mapping.mongo.MongoDatastore$6.doInDB(MongoDatastore.java:322)
	at org.grails.datastore.mapping.mongo.MongoDatastore.initializeIndices(MongoDatastore.java:286)
	at org.grails.datastore.mapping.mongo.MongoDatastore.createMongoTemplate(MongoDatastore.java:277)
	at org.grails.datastore.mapping.mongo.MongoDatastore.afterPropertiesSet(MongoDatastore.java:222)
	at org.grails.datastore.gorm.mongo.bean.factory.MongoDatastoreFactoryBean.getObject(MongoDatastoreFactoryBean.groovy:53)
	at org.grails.datastore.gorm.plugin.support.PersistenceContextInterceptorAggregator.postProcessBeanFactory(PersistenceContextInterceptorAggregator.groovy:109)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)
2013-08-24 15:34:29,680 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongoDatastore': FactoryBean threw exception on object creation; nested exception is org.springframework.dao.DataAccessResourceFailureException: Read operation to server /127.0.0.1:27017 failed on database petiko; nested exception is com.mongodb.MongoException$Network: Read operation to server /127.0.0.1:27017 failed on database petiko
	at org.grails.datastore.gorm.plugin.support.PersistenceContextInterceptorAggregator.postProcessBeanFactory(PersistenceContextInterceptorAggregator.groovy:109)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)
Caused by: org.springframework.dao.DataAccessResourceFailureException: Read operation to server /127.0.0.1:27017 failed on database petiko; nested exception is com.mongodb.MongoException$Network: Read operation to server /127.0.0.1:27017 failed on database petiko
	at org.grails.datastore.mapping.mongo.MongoDatastore.initializeIndices(MongoDatastore.java:286)
	at org.grails.datastore.mapping.mongo.MongoDatastore.createMongoTemplate(MongoDatastore.java:277)
	at org.grails.datastore.mapping.mongo.MongoDatastore.afterPropertiesSet(MongoDatastore.java:222)
	at org.grails.datastore.gorm.mongo.bean.factory.MongoDatastoreFactoryBean.getObject(MongoDatastoreFactoryBean.groovy:53)
	... 6 more
Caused by: com.mongodb.MongoException$Network: Read operation to server /127.0.0.1:27017 failed on database petiko
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:253)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:216)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:288)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:273)
	at com.mongodb.DBCollection.findOne(DBCollection.java:728)
	at com.mongodb.DBCollection.findOne(DBCollection.java:670)
	at com.mongodb.DBApiLayer$MyCollection.createIndex(DBApiLayer.java:342)
	at com.mongodb.DBCollection.createIndex(DBCollection.java:485)
	at com.mongodb.DBCollection.ensureIndex(DBCollection.java:561)
	at com.mongodb.DBCollection.ensureIndex(DBCollection.java:512)
	at org.grails.datastore.mapping.mongo.MongoDatastore$6.doInDB(MongoDatastore.java:322)
	... 10 more
Caused by: java.net.ConnectException: Connection refused
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at com.mongodb.DBPort._open(DBPort.java:223)
	at com.mongodb.DBPort.go(DBPort.java:125)
	at com.mongodb.DBPort.call(DBPort.java:92)
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:244)
	... 20 more
2013-08-24 15:34:29,681 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongoDatastore': FactoryBean threw exception on object creation; nested exception is org.springframework.dao.DataAccessResourceFailureException: Read operation to server /127.0.0.1:27017 failed on database petiko; nested exception is com.mongodb.MongoException$Network: Read operation to server /127.0.0.1:27017 failed on database petiko
	at org.grails.datastore.gorm.plugin.support.PersistenceContextInterceptorAggregator.postProcessBeanFactory(PersistenceContextInterceptorAggregator.groovy:109)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)
Caused by: org.springframework.dao.DataAccessResourceFailureException: Read operation to server /127.0.0.1:27017 failed on database petiko; nested exception is com.mongodb.MongoException$Network: Read operation to server /127.0.0.1:27017 failed on database petiko
	at org.grails.datastore.mapping.mongo.MongoDatastore.initializeIndices(MongoDatastore.java:286)
	at org.grails.datastore.mapping.mongo.MongoDatastore.createMongoTemplate(MongoDatastore.java:277)
	at org.grails.datastore.mapping.mongo.MongoDatastore.afterPropertiesSet(MongoDatastore.java:222)
	at org.grails.datastore.gorm.mongo.bean.factory.MongoDatastoreFactoryBean.getObject(MongoDatastoreFactoryBean.groovy:53)
	... 6 more
Caused by: com.mongodb.MongoException$Network: Read operation to server /127.0.0.1:27017 failed on database petiko
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:253)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:216)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:288)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:273)
	at com.mongodb.DBCollection.findOne(DBCollection.java:728)
	at com.mongodb.DBCollection.findOne(DBCollection.java:670)
	at com.mongodb.DBApiLayer$MyCollection.createIndex(DBApiLayer.java:342)
	at com.mongodb.DBCollection.createIndex(DBCollection.java:485)
	at com.mongodb.DBCollection.ensureIndex(DBCollection.java:561)
	at com.mongodb.DBCollection.ensureIndex(DBCollection.java:512)
	at org.grails.datastore.mapping.mongo.MongoDatastore$6.doInDB(MongoDatastore.java:322)
	... 10 more
Caused by: java.net.ConnectException: Connection refused
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at com.mongodb.DBPort._open(DBPort.java:223)
	at com.mongodb.DBPort.go(DBPort.java:125)
	at com.mongodb.DBPort.call(DBPort.java:92)
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:244)
	... 20 more
2013-08-24 15:34:29,681 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
org.springframework.dao.DataAccessResourceFailureException: Read operation to server /127.0.0.1:27017 failed on database petiko; nested exception is com.mongodb.MongoException$Network: Read operation to server /127.0.0.1:27017 failed on database petiko
	at org.grails.datastore.mapping.mongo.MongoDatastore.initializeIndices(MongoDatastore.java:286)
	at org.grails.datastore.mapping.mongo.MongoDatastore.createMongoTemplate(MongoDatastore.java:277)
	at org.grails.datastore.mapping.mongo.MongoDatastore.afterPropertiesSet(MongoDatastore.java:222)
	at org.grails.datastore.gorm.mongo.bean.factory.MongoDatastoreFactoryBean.getObject(MongoDatastoreFactoryBean.groovy:53)
	at org.grails.datastore.gorm.plugin.support.PersistenceContextInterceptorAggregator.postProcessBeanFactory(PersistenceContextInterceptorAggregator.groovy:109)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)
Caused by: com.mongodb.MongoException$Network: Read operation to server /127.0.0.1:27017 failed on database petiko
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:253)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:216)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:288)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:273)
	at com.mongodb.DBCollection.findOne(DBCollection.java:728)
	at com.mongodb.DBCollection.findOne(DBCollection.java:670)
	at com.mongodb.DBApiLayer$MyCollection.createIndex(DBApiLayer.java:342)
	at com.mongodb.DBCollection.createIndex(DBCollection.java:485)
	at com.mongodb.DBCollection.ensureIndex(DBCollection.java:561)
	at com.mongodb.DBCollection.ensureIndex(DBCollection.java:512)
	at org.grails.datastore.mapping.mongo.MongoDatastore$6.doInDB(MongoDatastore.java:322)
	... 10 more
Caused by: java.net.ConnectException: Connection refused
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at com.mongodb.DBPort._open(DBPort.java:223)
	at com.mongodb.DBPort.go(DBPort.java:125)
	at com.mongodb.DBPort.call(DBPort.java:92)
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:244)
	... 20 more
2013-08-24 15:34:29,682 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
com.mongodb.MongoException$Network: Read operation to server /127.0.0.1:27017 failed on database petiko
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:253)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:216)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:288)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:273)
	at com.mongodb.DBCollection.findOne(DBCollection.java:728)
	at com.mongodb.DBCollection.findOne(DBCollection.java:670)
	at com.mongodb.DBApiLayer$MyCollection.createIndex(DBApiLayer.java:342)
	at com.mongodb.DBCollection.createIndex(DBCollection.java:485)
	at com.mongodb.DBCollection.ensureIndex(DBCollection.java:561)
	at com.mongodb.DBCollection.ensureIndex(DBCollection.java:512)
	at org.grails.datastore.mapping.mongo.MongoDatastore$6.doInDB(MongoDatastore.java:322)
	at org.grails.datastore.mapping.mongo.MongoDatastore.initializeIndices(MongoDatastore.java:286)
	at org.grails.datastore.mapping.mongo.MongoDatastore.createMongoTemplate(MongoDatastore.java:277)
	at org.grails.datastore.mapping.mongo.MongoDatastore.afterPropertiesSet(MongoDatastore.java:222)
	at org.grails.datastore.gorm.mongo.bean.factory.MongoDatastoreFactoryBean.getObject(MongoDatastoreFactoryBean.groovy:53)
	at org.grails.datastore.gorm.plugin.support.PersistenceContextInterceptorAggregator.postProcessBeanFactory(PersistenceContextInterceptorAggregator.groovy:109)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)
Caused by: java.net.ConnectException: Connection refused
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at com.mongodb.DBPort._open(DBPort.java:223)
	at com.mongodb.DBPort.go(DBPort.java:125)
	at com.mongodb.DBPort.call(DBPort.java:92)
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:244)
	... 20 more
2013-08-24 15:34:29,683 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
java.net.ConnectException: Connection refused
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at com.mongodb.DBPort._open(DBPort.java:223)
	at com.mongodb.DBPort.go(DBPort.java:125)
	at com.mongodb.DBPort.call(DBPort.java:92)
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:244)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:216)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:288)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:273)
	at com.mongodb.DBCollection.findOne(DBCollection.java:728)
	at com.mongodb.DBCollection.findOne(DBCollection.java:670)
	at com.mongodb.DBApiLayer$MyCollection.createIndex(DBApiLayer.java:342)
	at com.mongodb.DBCollection.createIndex(DBCollection.java:485)
	at com.mongodb.DBCollection.ensureIndex(DBCollection.java:561)
	at com.mongodb.DBCollection.ensureIndex(DBCollection.java:512)
	at org.grails.datastore.mapping.mongo.MongoDatastore$6.doInDB(MongoDatastore.java:322)
	at org.grails.datastore.mapping.mongo.MongoDatastore.initializeIndices(MongoDatastore.java:286)
	at org.grails.datastore.mapping.mongo.MongoDatastore.createMongoTemplate(MongoDatastore.java:277)
	at org.grails.datastore.mapping.mongo.MongoDatastore.afterPropertiesSet(MongoDatastore.java:222)
	at org.grails.datastore.gorm.mongo.bean.factory.MongoDatastoreFactoryBean.getObject(MongoDatastoreFactoryBean.groovy:53)
	at org.grails.datastore.gorm.plugin.support.PersistenceContextInterceptorAggregator.postProcessBeanFactory(PersistenceContextInterceptorAggregator.groovy:109)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)
2013-08-24 15:34:29,683 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongoDatastore': FactoryBean threw exception on object creation; nested exception is org.springframework.dao.DataAccessResourceFailureException: Read operation to server /127.0.0.1:27017 failed on database petiko; nested exception is com.mongodb.MongoException$Network: Read operation to server /127.0.0.1:27017 failed on database petiko
	at org.grails.datastore.gorm.plugin.support.PersistenceContextInterceptorAggregator.postProcessBeanFactory(PersistenceContextInterceptorAggregator.groovy:109)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)
Caused by: org.springframework.dao.DataAccessResourceFailureException: Read operation to server /127.0.0.1:27017 failed on database petiko; nested exception is com.mongodb.MongoException$Network: Read operation to server /127.0.0.1:27017 failed on database petiko
	at org.grails.datastore.mapping.mongo.MongoDatastore.initializeIndices(MongoDatastore.java:286)
	at org.grails.datastore.mapping.mongo.MongoDatastore.createMongoTemplate(MongoDatastore.java:277)
	at org.grails.datastore.mapping.mongo.MongoDatastore.afterPropertiesSet(MongoDatastore.java:222)
	at org.grails.datastore.gorm.mongo.bean.factory.MongoDatastoreFactoryBean.getObject(MongoDatastoreFactoryBean.groovy:53)
	... 6 more
Caused by: com.mongodb.MongoException$Network: Read operation to server /127.0.0.1:27017 failed on database petiko
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:253)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:216)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:288)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:273)
	at com.mongodb.DBCollection.findOne(DBCollection.java:728)
	at com.mongodb.DBCollection.findOne(DBCollection.java:670)
	at com.mongodb.DBApiLayer$MyCollection.createIndex(DBApiLayer.java:342)
	at com.mongodb.DBCollection.createIndex(DBCollection.java:485)
	at com.mongodb.DBCollection.ensureIndex(DBCollection.java:561)
	at com.mongodb.DBCollection.ensureIndex(DBCollection.java:512)
	at org.grails.datastore.mapping.mongo.MongoDatastore$6.doInDB(MongoDatastore.java:322)
	... 10 more
Caused by: java.net.ConnectException: Connection refused
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at com.mongodb.DBPort._open(DBPort.java:223)
	at com.mongodb.DBPort.go(DBPort.java:125)
	at com.mongodb.DBPort.call(DBPort.java:92)
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:244)
	... 20 more
